### ISSUE TITLE
Wrong usage zones

### ISSUE THREAD

**Issue by deseven** [loiste-interactive/Open-Sewer-Issues#122]
Related to #81. Here are a couple of examples from the market.

I'm standing in the corner but i still can sell bottles if i press E.
![20181202001753_1](https://user-images.githubusercontent.com/1761803/49334061-f4db9e80-f5cb-11e8-9d3b-73c29c604bfa.jpg)

I'm standing in the corner to the right of the trader, i still can speak with him if i press E.
![20181202001817_1](https://user-images.githubusercontent.com/1761803/49334062-0f157c80-f5cc-11e8-9a0e-87b00654e6be.jpg)

**Comment by Oskutin** [comment]
This is now fixed with the new system
