### ISSUE TITLE
When buying something from the pharmacy a misleading tooltip "Not Accepted" is shown

### ISSUE THREAD

**Issue by Kumasasa** [loiste-interactive/Open-Sewer-Issues#183]
![20181206210450_1](https://user-images.githubusercontent.com/12480900/49609219-22916080-f99b-11e8-9469-741f76701c7b.jpg)
That drug dealer simply should accept my money, nothing else...

**Comment by Oskutin** [comment]
Possibly fixed this now, for a good. Object ownership shouldn't change now.
Or atleast it has became damn rare and hard to repro.
