### ISSUE TITLE
When there are more than four dialogue options there is no scroll bar

### ISSUE THREAD

**Issue by Kumasasa** [loiste-interactive/Open-Sewer-Issues#212]
When there are 4+ dialogue option there is no scroll bar, scrolling works **very slowly** via scroll wheel, but that also changes FOV
![20181208132942_1](https://user-images.githubusercontent.com/12480900/49685953-8deb4780-faed-11e8-8e82-522e6901a135.jpg)

**Comment by Zuntti** [comment]
Fixed.
