### ISSUE TITLE
Sticky corners / Weird Collision 

### ISSUE THREAD

**Issue by Aetsuki** [loiste-interactive/Open-Sewer-Issues#282]
Will update this one as I find them, there's a few spots I've found consistantly.
https://i.imgur.com/dOzf0NI.jpg

**Comment by Oskutin** [comment]
Getting stuck there?

**Comment by Aetsuki** [comment]
Yeah, there's a few spots I've found where if you run at them you'll fling into the air or get stuck in a permanent falling animation. I'll boot up now and see if I can reproduce the other two I remember

**Comment by Oskutin** [comment]
Fixed the first

**Comment by Aetsuki** [comment]
Another spot, this one just infront of the starting area. This one I accidentally ran into by bouncing off the bag of cement when I first launched the game, which I can't reproduce. https://i.imgur.com/wzhbAPu.jpg

**Comment by Oskutin** [comment]
Also fixed

**Comment by Aetsuki** [comment]
https://i.imgur.com/M1eMoNy.jpg
If you run at this space between the pavement and the garden fence you float to the other side. If you stand on it, you're stuck there for the rest of your life. Spot's just out front of the tenement.
