### ISSUE TITLE
Should be possible to pay Rob full cost immediately if money is available.

### ISSUE THREAD

**Issue by Aetsuki** [loiste-interactive/Open-Sewer-Issues#284]

**Comment by Kumasasa** [comment]
This is working by design:
Keep in mind that the renovation takes some time (also not a bug).
If the player would be standing in front of the tenement when the renovation timer times out, then the renovation would insta-spawn right before his eyes.

**Comment by Aetsuki** [comment]
I'm aware of the timer, but fair point on the insta-spawn. Still that should be resolvable by having the same sort of confirmation dialogue with Rob. It's just slightly easier on money management if I can just throw all the money in at once.
