### ISSUE TITLE
Trader by Osmo Olut red pipeline sells item he doesn't accept

### ISSUE THREAD

**Issue by Aetsuki** [loiste-interactive/Open-Sewer-Issues#285]
https://i.imgur.com/1r91OP9.png

**Comment by Kumasasa** [comment]
IMO not a bug.
It's up to the trader just to accept a selection of his portfolio.

**Comment by Oskutin** [comment]
Well, if that junk trader sells/buys alcohol and rollies, he should also buy mushrooms.

**Comment by Oskutin** [comment]
Now he accepts mushrooms.
