### ISSUE TITLE
Autosave w/ adjustable intervals

### ISSUE THREAD

**Issue by Aetsuki** [loiste-interactive/Open-Sewer-Issues#287]
Option to set up an autosave every x amount of minutes. Right now there's alot of nifty little spots that can kill you, and with some of the more grindy work and scarcity of stuff an autosave would be nice just in general. 

It was probably just me being stupid but as an example I slipped through this spot https://i.imgur.com/mW7uXa8.jpg
And died pretty much instantly, resetting my progress about half an hour to a save I took while testing for wonky collision. There's actually quite a few spots like this where you can slip into a death area because of how the character controls in third person.

I do see that there was a bug related to autosaves in which autosaving may have been disabled before release, but I'm not certain on what did go on there.

**Comment by Oskutin** [comment]
We had buggy autosaving upon waking up, but autosaves within some intervals sounds better

**Comment by Epok13** [comment]
Yep, just the same: I died in the same spot trying to collect bottles... Autosave would be great.

**Comment by Oskutin** [comment]
There's now autosave when using toilets.
