### ISSUE TITLE
Permanently have one more night at the inn

### ISSUE THREAD

**Issue by Aetsuki** [loiste-interactive/Open-Sewer-Issues#289]
Innkeeper seems to have a soft spot for me. It's been about a week ingame since I bought a night at the inn, every time I talk to him he says I have a night left, and I still have access to the room. Also notable is it says 1 nights instead of night.

**Comment by Oskutin** [comment]
Fixed.
It didn't count down time if you loaded a game.

**Comment by Epok13** [comment]
Hum, it seems the bug is still therein 0.1.2.

**Comment by Oskutin** [comment]
Fixed (again).
