### ISSUE TITLE
Bug in controls menu.

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#295]
If you click to "Disabled" - audio options opens on background.
![gif](https://user-images.githubusercontent.com/4739426/49957798-f84f1e00-ff19-11e8-9aa6-dff4995414fe.gif)

**Comment by Leshiy-ART** [comment]
And the same problem in Display menu, if we click to word between - and +

**Comment by Zuntti** [comment]
Fixed.
