### ISSUE TITLE
Stuck in junk

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#297]
![image](https://user-images.githubusercontent.com/4739426/49959016-78c34e00-ff1d-11e8-9036-1af0f9d9b776.png)

![20181213212453_1](https://user-images.githubusercontent.com/4739426/49959050-92649580-ff1d-11e8-9bed-66dfc5937a92.jpg)

**Comment by Oskutin** [comment]
Fixed
