### ISSUE TITLE
Stuck in my tenement (1st floor)

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#298]
Without renovation.
![20181213212701_1](https://user-images.githubusercontent.com/4739426/49959210-fd15d100-ff1d-11e8-9f96-b3a8a4d1020e.jpg)

**Comment by Leshiy-ART** [comment]
And there...
![20181213213018_1](https://user-images.githubusercontent.com/4739426/49959331-57169680-ff1e-11e8-96d9-da3574571259.jpg)

**Comment by Oskutin** [comment]
Fixed
