### ISSUE TITLE
Fall out of world.

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#299]
![image](https://user-images.githubusercontent.com/4739426/49960305-e624ae00-ff20-11e8-9637-a4dc3781a3ea.png)

![gif](https://user-images.githubusercontent.com/4739426/49960325-ef157f80-ff20-11e8-9709-0391a6176d91.gif)

**Comment by Oskutin** [comment]
This should be fixed already.

**Comment by Oskutin** [comment]
Oh, it wasn't but it is now.
