### ISSUE TITLE
Door "open" but close. And no sound on another.

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#300]
![image](https://user-images.githubusercontent.com/4739426/49960771-fee19380-ff21-11e8-996c-b7e0e18cf9e9.png)

![image](https://user-images.githubusercontent.com/4739426/49960794-0b65ec00-ff22-11e8-831a-2283b02ba746.png)

No locked sound on this door:

![image](https://user-images.githubusercontent.com/4739426/49960895-46681f80-ff22-11e8-85f3-863df2830268.png)

![image](https://user-images.githubusercontent.com/4739426/49960949-6e578300-ff22-11e8-8747-5226499a2c96.png)

**Comment by Oskutin** [comment]
Fixed
