### ISSUE TITLE
Stuck on railing and hole on clip.

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#301]
Here:
![image](https://user-images.githubusercontent.com/4739426/49961176-048ba900-ff23-11e8-9045-a19057650c99.png)

And here along the entire length:
![image](https://user-images.githubusercontent.com/4739426/49961304-6fd57b00-ff23-11e8-9b0f-38865a8bd16b.png)

![image](https://user-images.githubusercontent.com/4739426/49961332-811e8780-ff23-11e8-9153-51ea2ac134bc.png)

Here are hole:
![image](https://user-images.githubusercontent.com/4739426/49961673-5123b400-ff24-11e8-815e-a02fe5ff2ccd.png)

![gif](https://user-images.githubusercontent.com/4739426/49961634-39e4c680-ff24-11e8-9efc-ab28da36be60.gif)

**Comment by Oskutin** [comment]
Fixed
