### ISSUE TITLE
Stuck on dumpster

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#302]
![image](https://user-images.githubusercontent.com/4739426/49961966-03f41200-ff25-11e8-80bd-999f959be09e.png)

![image](https://user-images.githubusercontent.com/4739426/49962020-225a0d80-ff25-11e8-8506-313207e9668c.png)

I have no idea what I forgot there...

**Comment by Oskutin** [comment]
Fxd
