### ISSUE TITLE
No collision on fence model.

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#303]
![image](https://user-images.githubusercontent.com/4739426/49962303-f8551b00-ff25-11e8-837f-10c098915771.png)

![image](https://user-images.githubusercontent.com/4739426/49962460-5da90c00-ff26-11e8-9b41-acd2a5e21bf7.png)

**Comment by Oskutin** [comment]
Not putting head in fence, anymore
