### ISSUE TITLE
Stuck near sauna.

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#304]
![image](https://user-images.githubusercontent.com/4739426/49962750-24bd6700-ff27-11e8-845e-0c8550de9e20.png)

![image](https://user-images.githubusercontent.com/4739426/49962772-34d54680-ff27-11e8-981d-88c0caed2fea.png)

**Comment by Oskutin** [comment]
Fixed
