### ISSUE TITLE
Path out of map.

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#312]
YES! I'M FREE!
![image](https://user-images.githubusercontent.com/4739426/49966248-87673080-ff30-11e8-8165-5e60d46e2495.png)

Path to freedom.
![image](https://user-images.githubusercontent.com/4739426/49966347-d1501680-ff30-11e8-8ca7-be0893cc87a9.png)

![image](https://user-images.githubusercontent.com/4739426/49966522-40c60600-ff31-11e8-9a0a-a6f3904287f1.png)

**Comment by Leshiy-ART** [comment]
![gif](https://user-images.githubusercontent.com/4739426/49970173-8b4c8000-ff3b-11e8-9025-848d71be27dc.gif)

**Comment by Oskutin** [comment]
Remember, that you're always going to stay in Open Sewer.
