### ISSUE TITLE
Stuck when climb on ladder near sauna.

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#313]
![image](https://user-images.githubusercontent.com/4739426/49967302-7f5cc000-ff33-11e8-8e25-c9607b4f8c5e.png)

![image](https://user-images.githubusercontent.com/4739426/49967246-5b00e380-ff33-11e8-830b-d88568afd116.png)

**Comment by Oskutin** [comment]
Fixed
