### ISSUE TITLE
Stuck near Osmo Olut

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#314]
![image](https://user-images.githubusercontent.com/4739426/49967410-d2367780-ff33-11e8-9676-16534f7834c1.png)

![image](https://user-images.githubusercontent.com/4739426/49967392-c2b72e80-ff33-11e8-9fa1-f3e2657b70af.png)

**Comment by Oskutin** [comment]
Fixed
