### ISSUE TITLE
Path to closed locations.

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#316]
![image](https://user-images.githubusercontent.com/4739426/49968573-445c8b80-ff37-11e8-97a5-ec2abd3817c5.png)

![image](https://user-images.githubusercontent.com/4739426/49968533-2131dc00-ff37-11e8-9ee0-4bbd7bcc7849.png)

**Comment by Oskutin** [comment]
Um.. Fxd
