### ISSUE TITLE
Jump out of world.

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#318]
![image](https://user-images.githubusercontent.com/4739426/49969209-0f513880-ff39-11e8-9c10-f201d46a523e.png)

![image](https://user-images.githubusercontent.com/4739426/49969125-d1ecab00-ff38-11e8-8891-1bd26e8f4adf.png)

![gif](https://user-images.githubusercontent.com/4739426/49969220-17a97380-ff39-11e8-8b13-5a2ccac277da.gif)

**Comment by Oskutin** [comment]
Fixed
