### ISSUE TITLE
White dots appear to the pause menu after saving

### ISSUE THREAD

**Issue by paavohuhtala** [loiste-interactive/Open-Sewer-Issues#323]
After saving the game via the save menu, two small white dots appear on the far left of the pause menu, about 1/3 the way down. They remain there even after closing and reopening the menu.

(Expand to see them; they're right next to the border)
![open_sewer_2018-12-15_11-09-25](https://user-images.githubusercontent.com/803180/50041243-787c9d00-005a-11e9-95fa-62b0588c1a66.jpg)

The game is running at 2560x1440, which might cause the issue?

**Comment by Zuntti** [comment]
Fixed.
