### ISSUE TITLE
Junk Trader broken

### ISSUE THREAD

**Issue by AbueloNemesis** [loiste-interactive/Open-Sewer-Issues#326]
At some point he started selling everything without any charge of coins (price is shown, but just doesn't charge it when buying), and also he's not buying things anymore despite having plenty of room for it.

Not sure what triggered this. Maybe it started when I bought from him some turnips for 0 OC each, but I can't assure it was the cause.

**Comment by Oskutin** [comment]
He run out of money. He will regain some money after short period of time.
In new version (currently in public "untested" branch), traders have an indicator telling if they have ran out of money.
