### ISSUE TITLE
This area feels too empty, add something there

### ISSUE THREAD

**Issue by deseven** [loiste-interactive/Open-Sewer-Issues#328]
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/1761803/50054828-7c85e900-0146-11e9-88ca-40556a9903b1.png">

**Comment by Oskutin** [comment]
I was planning to add somekind of display of moonshining tools there.

**Comment by CVariable** [comment]
Maybe you can buy some upgrades for your in-tenement equipment there?

**Comment by Oskutin** [comment]
Added some detail
