### ISSUE TITLE
Tenement management view keeps mentioning resident name after changing selection

### ISSUE THREAD

**Issue by Epok13** [loiste-interactive/Open-Sewer-Issues#333]
If you select an apartment containing a resident, the resident name will stay displayed even if you switch apartment selection.

**Comment by CVariable** [comment]
Not sure if only visual, as the game will allow me to evict the resident out of the apartment, even if he rented and lives in a different apartment.
![20181217215342_1](https://user-images.githubusercontent.com/45665371/50252901-cee63480-03e8-11e9-8398-7b5e8e3e1475.jpg)

**Comment by Epok13** [comment]
Yes, however if you click the button, this would play the sound and make the button disappear, but NOT evict the resident.

**Comment by Oskutin** [comment]
I believe this is fixed now.
