### ISSUE TITLE
Moving Items In General Trader's Inventory "Sells" Them to Him

### ISSUE THREAD

**Issue by WaterCurses** [loiste-interactive/Open-Sewer-Issues#341]
Well that was a quick three grand. Was using the general traders inventory to split a stack of something that I wanted to buy and realized I was getting cash for it. Realized that I could "sell" each stack in his inventory back to him by moving it in his inventory.

**Comment by Epok13** [comment]
OK, here is a step-by-step for reproducing the two traders inventory bugs:
1:
- Go to alco store,
- Interact with the trader to open the trading view,
- Right-click on a stack and deposit it on another stack in the seller inventory,
- The stack moves to your inventory for free, double-click on it to sell it back to the seller.

2:
- Go to general trader,
- Interact with the trader to open the trading view,
- Right-click on a stack and deposit it on an empty box in the seller inventory,
- You gain the price of the stack.

**Comment by Oskutin** [comment]
Partially fixed by now.
