### ISSUE TITLE
Place we usually get stuck

### ISSUE THREAD

**Issue by Epok13** [loiste-interactive/Open-Sewer-Issues#342]
Get immediately right when leaving your tenement, then left before crossing the canal. Between the building and the canal is a place we can very difficultly reach, and we frequently get stuck in:

![20181218210121_1](https://user-images.githubusercontent.com/8208481/50301420-95183b00-0487-11e9-9814-a82a91c95a6d.jpg)

**Comment by Oskutin** [comment]
Should be fixed now
