### ISSUE TITLE
Seeing through the map

### ISSUE THREAD

**Issue by Epok13** [loiste-interactive/Open-Sewer-Issues#343]
Next to the WC on the south of the map, get up the stairs and stay in the middle of it:

![20181218203725_1](https://user-images.githubusercontent.com/8208481/50301521-ddcff400-0487-11e9-9196-01f7ba1391ba.jpg)

Then move the camera up and you can see through the map:

![20181218203721_1](https://user-images.githubusercontent.com/8208481/50301546-efb19700-0487-11e9-8d4f-937a4935645c.jpg)

**Comment by Oskutin** [comment]
Fixed
