### ISSUE TITLE
Bucket Duplication

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Open-Sewer-Issues#345]
When smelting sugar beets in the sauna, you get 2 buckets of sugar water for each bucket that's used. Then, after drying that, you get one bucket per sugar water. That means, you get twice the buckets you had before. 
![20181221144800_1](https://user-images.githubusercontent.com/45665371/50373565-42eb2d00-05e1-11e9-82b4-5ec505085844.jpg)

**Comment by Oskutin** [comment]
Already fixed in the upcoming update.
