### ISSUE TITLE
Oven extraction issues

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Open-Sewer-Issues#346]
When extracting stuff from the oven and not removing the stack once it is full (for example 8 sugar), all sugar bags you extract afterwards seem to vanish. 
![20181221144808_1](https://user-images.githubusercontent.com/45665371/50373574-729a3500-05e1-11e9-82ca-45a294b1d8ed.jpg)

**Comment by Oskutin** [comment]
So, if you have full stack of sugar in the inventory, it won't add anymore sugar?

**Comment by Oskutin** [comment]
Okay, i may have fixed this now.

**Comment by Oskutin** [comment]
Yeah, works now.
