### ISSUE TITLE
Intro timing is off (playtesting branch)

### ISSUE THREAD

**Issue by Kumasasa** [loiste-interactive/Open-Sewer-Issues#352]
* the white phase until fading out is very long
* the timing is off: the "Obenseuer" -> "Open Sewer" isn't on the gate but is show while the camera is flying
![20190102224118_1](https://user-images.githubusercontent.com/12480900/50614062-e7257b80-0edf-11e9-8f1b-fc7415911784.jpg)
![20190102224136_1](https://user-images.githubusercontent.com/12480900/50614063-e7257b80-0edf-11e9-94ed-1856a2b77159.jpg)
![20190102224140_1](https://user-images.githubusercontent.com/12480900/50614064-e7257b80-0edf-11e9-90c8-5f829d79bf5d.jpg)
[output_log.txt](https://github.com/loiste-interactive/Open-Sewer-Issues/files/2722170/output_log.txt)

**Comment by Kumasasa** [comment]
Logfile is spammed with 

> Array index (1) is out of bounds (size=0)

**Comment by Kumasasa** [comment]
I'm pretty sure that's not meant to be like that:
> NullReferenceException: Object reference not set to an instance of an object
>   at LoadAppearance.UpdateAppearance () [0x00000] in <filename unknown>:0 
>   at LoadAppearance+<wait>c__Iterator0.MoveNext () [0x00000] in <filename unknown>:0 
>   at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 
>  
> (Filename:  Line: -1)
> 
> Something happens yes

**Comment by skyem123** [comment]
The intro doesn't even load properly on my worse than turnip laptop.
