### ISSUE TITLE
Jump bone bug

### ISSUE THREAD

**Issue by Z-O-M-B-I-E** [loiste-interactive/Open-Sewer-Issues#354]
You can notice a bug with legs when jumping.
![20190117153320_1](https://user-images.githubusercontent.com/46783282/51343078-8fbe0880-1aa6-11e9-8132-20ab3ca554cb.jpg)
![20190117153321_1](https://user-images.githubusercontent.com/46783282/51343079-90569f00-1aa6-11e9-8965-d19aefb67ab4.jpg)
![20190117153323_1](https://user-images.githubusercontent.com/46783282/51343081-90569f00-1aa6-11e9-90a8-cfc7fb97fae7.jpg)
![20190117153324_1](https://user-images.githubusercontent.com/46783282/51343082-90569f00-1aa6-11e9-81b3-14f24851e8e0.jpg)
![20190117153326_1](https://user-images.githubusercontent.com/46783282/51343084-90569f00-1aa6-11e9-977f-6d8452c3e0a8.jpg)

**Comment by Kumasasa** [comment]
What is the bug here? Cannot see it from the screenshots.

**Comment by Z-O-M-B-I-E** [comment]
> What is the bug here? Cannot see it from the screenshots.

See leg in jump, Texture bug.

**Comment by deseven** [comment]
kneecaps are falling off :D

**Comment by riksaa** [comment]
Fixed.
