### ISSUE TITLE
No collision

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#355]
![image](https://user-images.githubusercontent.com/4739426/51350104-5ee6cf00-1ab8-11e9-8b94-e2cf5678fab2.png)

![image](https://user-images.githubusercontent.com/4739426/51350138-7920ad00-1ab8-11e9-87c2-adf556231d12.png)

**Comment by Oskutin** [comment]
Fixed
