### ISSUE TITLE
Stuck behind the fence

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#356]
![image](https://user-images.githubusercontent.com/4739426/51350203-a0777a00-1ab8-11e9-9817-c09cfe4f3c1a.png)

![image](https://user-images.githubusercontent.com/4739426/51350192-95bce500-1ab8-11e9-8e77-746cd800b86f.png)

**Comment by Oskutin** [comment]
Fixed
