### ISSUE TITLE
Escape from Open Sewer!

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#358]
I'm free! Again! Near start area.

![20190118004027_1](https://user-images.githubusercontent.com/4739426/51350806-31028a00-1aba-11e9-8c32-6f5019fcc9eb.jpg)

![gif](https://user-images.githubusercontent.com/4739426/51350982-a2423d00-1aba-11e9-9fe0-16d0e27ade84.gif)

**Comment by Oskutin** [comment]
Nope.
