### ISSUE TITLE
Stuck behind chapel.

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#365]
![image](https://user-images.githubusercontent.com/4739426/51352526-e6cfd780-1abe-11e9-9198-f77c9d258daa.png)

![image](https://user-images.githubusercontent.com/4739426/51352537-edf6e580-1abe-11e9-9075-d67607aa7bfc.png)

**Comment by Oskutin** [comment]
Fixed
