### ISSUE TITLE
Ground behind church without collision

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#366]
left and right of the church.
![image](https://user-images.githubusercontent.com/4739426/51352690-71b0d200-1abf-11e9-951a-83db69688696.png)

![image](https://user-images.githubusercontent.com/4739426/51352724-88efbf80-1abf-11e9-9555-f45135a87e89.png)

**Comment by Oskutin** [comment]
Not anymore
