### ISSUE TITLE
Wall without collision

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#368]
![20190118013424_1](https://user-images.githubusercontent.com/4739426/51353308-5777f380-1ac1-11e9-80dc-6eb2991d82eb.jpg)

![image](https://user-images.githubusercontent.com/4739426/51353314-61015b80-1ac1-11e9-9a00-eece4ce7ff66.png)

![image](https://user-images.githubusercontent.com/4739426/51353338-6fe80e00-1ac1-11e9-83a1-f6157d8ff626.png)

**Comment by Oskutin** [comment]
Wall is 'hardwood' now
