### ISSUE TITLE
Escape from Open Sewer through SAUNA

### ISSUE THREAD

**Issue by Leshiy-ART** [loiste-interactive/Open-Sewer-Issues#372]
![20190118020401_1](https://user-images.githubusercontent.com/4739426/51354832-fd2d6180-1ac5-11e9-94d5-6f205ef5493d.jpg)

![gif](https://user-images.githubusercontent.com/4739426/51354952-76c54f80-1ac6-11e9-9b13-35be940600c6.gif)

**Comment by Oskutin** [comment]
F
