### ISSUE TITLE
A lot of collision issues in cemetry

### ISSUE THREAD

**Issue by Epok13** [loiste-interactive/Open-Sewer-Issues#374]
Already mentioned it in steam bug tracker, but as you seem in a mood of collision bug fixing, here it is again: basically, all graveyards which are not actual graveyards can be passed through:

![20190120200258_1](https://user-images.githubusercontent.com/8208481/51443799-b5d5e980-1cee-11e9-9d8d-c15a96966d61.jpg)
![20190120200314_1](https://user-images.githubusercontent.com/8208481/51443801-b8d0da00-1cee-11e9-8a24-57abe47cedff.jpg)
![20190120200325_1](https://user-images.githubusercontent.com/8208481/51443802-bb333400-1cee-11e9-85da-2bacabada5a3.jpg)
![20190120200334_1](https://user-images.githubusercontent.com/8208481/51443804-bc646100-1cee-11e9-92c7-17b0da35d213.jpg)
![20190120200346_1](https://user-images.githubusercontent.com/8208481/51443805-bec6bb00-1cee-11e9-8610-bf0e41d4eb5a.jpg)

**Comment by Epok13** [comment]
And one more on the school yard just next:

![20190120200735_1](https://user-images.githubusercontent.com/8208481/51443835-1fee8e80-1cef-11e9-8bda-552652d9182f.jpg)

**Comment by Oskutin** [comment]
Fixed
