### ISSUE TITLE
Some people still say time in wrong format

### ISSUE THREAD

**Issue by deseven** [loiste-interactive/Open-Sewer-Issues#376]
I guess you have to check if you need to add zero.

![image](https://user-images.githubusercontent.com/1761803/53042538-c791e480-3486-11e9-8965-02d9530b35e2.png)

**Comment by CitadelCore** [comment]
Just use https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tostring ?

**Comment by Zuntti** [comment]
Fixed.
