### ISSUE TITLE
Open Sewer girls are sick and beardy

### ISSUE THREAD

**Issue by deseven** [loiste-interactive/Open-Sewer-Issues#379]
![image](https://user-images.githubusercontent.com/1761803/53043887-cd3cf980-3489-11e9-8521-68fe3d46860f.png)

**Comment by deseven** [comment]
Looks like this a global issue
![image](https://user-images.githubusercontent.com/1761803/53045184-3ffba400-348d-11e9-9a53-620c746673fb.png)

**Comment by Zuntti** [comment]
Fixed.
