### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by deseven** [loiste-interactive/Open-Sewer-Issues#38]
Sometimes i get constant 45+ fps even on perkele settings, but in some locations it drops below 20, like in front of the bazar, while there is nothing too complex on the screen.

**Comment by deseven** [comment]
Current playtesting branch - max fps is MUCH better (so is average, obviously) and i'm talking about at least 2 times improvement on my setup, but periodic freezes/drops are still here.

**Comment by CVariable** [comment]
There's still some areas that are completely insufferable, and it sometimes happens at random aswell. 
![20190310153449_2](https://user-images.githubusercontent.com/45665371/54092458-a4bf6580-438c-11e9-9095-db5a4abcb7f2.jpg)
As you can see in the picture, no real bottleneck is identifyable, and still, the game sits at 19fps. In other areas however, the game runs at 60fps without stutter.
