### ISSUE TITLE
Invisible wall

### ISSUE THREAD

**Issue by Epok13** [loiste-interactive/Open-Sewer-Issues#388]
Unable to pass through:

![20190222180657_1](https://user-images.githubusercontent.com/8208481/53258414-dff34080-36cc-11e9-8a7a-5b6668cee088.jpg)

Just bumping on an invisible wall.

**Comment by Oskutin** [comment]
Can't reproduce.

**Comment by Epok13** [comment]
Yup, from previous version.
Attached the save file.

[slot1_save.zip](https://github.com/loiste-interactive/Open-Sewer-Issues/files/2895335/slot1_save.zip)

**Comment by Epok13** [comment]
This issue seems to apply for a whole chunk of map. Here are the borders I can't pass through:

![20190222212845_1](https://user-images.githubusercontent.com/8208481/53269399-0c1cba80-36e9-11e9-82cf-7a94e44aa7fd.jpg)

![20190222212900_1](https://user-images.githubusercontent.com/8208481/53269403-117a0500-36e9-11e9-9c82-ee0622db0c11.jpg)

![20190222212908_1](https://user-images.githubusercontent.com/8208481/53269408-150d8c00-36e9-11e9-9216-b6f7333b62fd.jpg)

**Comment by Zuntti** [comment]
Fixed.
