### ISSUE TITLE
Unable to eat

### ISSUE THREAD

**Issue by Epok13** [loiste-interactive/Open-Sewer-Issues#391]
From my inventory: able to click "eat", but nothing happens:
![20190222213903_1](https://user-images.githubusercontent.com/8208481/53269871-52bee480-36ea-11e9-8992-7b6f06b997c7.jpg)

Does not apply to "drink", which is OK.

**Comment by Oskutin** [comment]
Does eating work if you start a new game?

**Comment by Epok13** [comment]
Just tried it. Yes, it works.

However, I wish I don't have to start from scratch again, as the save editor can't be used to set the tenement state, and it takes long to upgrade it...
