### ISSUE TITLE
All containers seem empty

### ISSUE THREAD

**Issue by Epok13** [loiste-interactive/Open-Sewer-Issues#393]
When upgrading from a previous version save. Includes traders inventories:

![20190222214518_1](https://user-images.githubusercontent.com/8208481/53270194-5868fa00-36eb-11e9-80f8-e890b62365d6.jpg)

![20190222214921_1](https://user-images.githubusercontent.com/8208481/53270493-21dfaf00-36ec-11e9-9405-def0c5a79cef.jpg)

**Comment by Oskutin** [comment]
This is again related to old saves?

**Comment by Epok13** [comment]
All my comments done yesterday are related to saves from the previous version.

**Comment by Oskutin** [comment]
Ah yes, loading save blanks inventories and replaces them with loaded stuff.
Those storages should respawn after some ingame hours/days.
