### ISSUE TITLE
Doors opening the wrong way

### ISSUE THREAD

**Issue by Epok13** [loiste-interactive/Open-Sewer-Issues#395]
Makes it hard to get through as the door hits the player.

Own tenement doors:
![20190222214838_1](https://user-images.githubusercontent.com/8208481/53270563-58b5c500-36ec-11e9-9a98-1442cf42af7d.jpg)
![20190222214842_1](https://user-images.githubusercontent.com/8208481/53270565-5b181f00-36ec-11e9-8b7b-b7c2505603dd.jpg)

General trader  door:
![20190222215044_1](https://user-images.githubusercontent.com/8208481/53270587-68cda480-36ec-11e9-8166-003d17b5bd09.jpg)
![20190222215058_1](https://user-images.githubusercontent.com/8208481/53270593-6bc89500-36ec-11e9-897c-f7d6aa6732ba.jpg)

**Comment by Zuntti** [comment]
Fixed general trader door.

**Comment by Epok13** [comment]
One more: Osmo olut fence door:
![20190226202510_1](https://user-images.githubusercontent.com/8208481/53440943-0505ed00-3a06-11e9-8be9-b4ce2e534d72.jpg)
![20190226202516_1](https://user-images.githubusercontent.com/8208481/53440953-0afbce00-3a06-11e9-9b99-b3890010be8c.jpg)

**Comment by Epok13** [comment]
One more: "House" main door:
![20190227110620_1](https://user-images.githubusercontent.com/8208481/53482588-d7f62080-3a7f-11e9-9aa2-0c23b26e3a28.jpg)

**Comment by Oskutin** [comment]
This should work now.
