### ISSUE TITLE
Walking too fast over refuse/snow piles causes you to fly over them and die from fall damage.

### ISSUE THREAD

**Issue by ReverendV92** [loiste-interactive/Open-Sewer-Issues#396]
Pretty much as it says on the tin. Every time I'm using sprint speed and I go over a snow/trash pile over the apex, I can pretty much expect myself to die and eat it from fall damage.

If I had to guess, it's because I'm essentially going terminal velocity off the pile and the game doesn't know the difference between that and me jumping off the tenement.

**Comment by Oskutin** [comment]
There were bug with the fall damage, it should be fixed now.
