### ISSUE TITLE
Issues with Menu Performance with simple Fix

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Open-Sewer-Issues#397]
![grafik](https://user-images.githubusercontent.com/45665371/53306400-ea5c3880-388c-11e9-880b-db7372688ebf.png)
When starting the game, in my case in 1080p High, the Menu performance is less than optimal - 23 to 25 fps, and stuttery.
A simple way to fix that is to go into the Display menu and clicking apply. 
No matter if you changed any settings, performance instantly optimizes and the stutter disappears.
No idea what causes it, but having the menu call for apply display options upon Game startup may be a fix enough.

**Comment by Zuntti** [comment]
Added apply display to game startup.
