### ISSUE TITLE
Unable interact with cook barrel in my appartmennt

### ISSUE THREAD

**Issue by Epok13** [loiste-interactive/Open-Sewer-Issues#400]
Seems this one is not fixed (0.1.4) :
![20190226201407_1](https://user-images.githubusercontent.com/8208481/53439898-8a3bd280-3a03-11e9-9adb-6410888735d6.jpg)

**Comment by Oskutin** [comment]
What level apartment? Does that atleast open the UI?

**Comment by Epok13** [comment]
Ground level (my apartment). No interface opens when I press "use".

**Comment by Oskutin** [comment]
Fixed
