### ISSUE TITLE
Passing through doors in my appartment

### ISSUE THREAD

**Issue by Epok13** [loiste-interactive/Open-Sewer-Issues#401]
Cant open the inner doors (no prompt at all):

![20190226201344_1](https://user-images.githubusercontent.com/8208481/53439944-a50e4700-3a03-11e9-9499-75e12d7c0628.jpg)
![20190226201403_1](https://user-images.githubusercontent.com/8208481/53439956-a93a6480-3a03-11e9-9a88-72b3ba0cf1be.jpg)

But passing through:
![20190226201354_1](https://user-images.githubusercontent.com/8208481/53440004-cb33e700-3a03-11e9-9b32-97ed8d1e88ce.jpg)
![20190226201352_1](https://user-images.githubusercontent.com/8208481/53439968-b0617280-3a03-11e9-88a1-cb6a12c44f20.jpg)

**Comment by Scarchu** [comment]
Same thing here, happened after buying furniture. Also i guess you can't go up the stairs?

**Comment by Epok13** [comment]
Just tried it, no problem to go upstairs and up to the roof.

**Comment by Scarchu** [comment]
Strange... when this happened for me, i couldn't even reach the stiars.

**Comment by Epok13** [comment]
Same issue in "House" (the one with the lockpickable door near bazaar):
![20190227110529_1](https://user-images.githubusercontent.com/8208481/53482622-f0663b00-3a7f-11e9-82c0-e117bfc3939c.jpg)

**Comment by Zuntti** [comment]
Fixed House door.

**Comment by Oskutin** [comment]
Should be fixed now
