### ISSUE TITLE
Various issues with doors

### ISSUE THREAD

**Issue by Epok13** [loiste-interactive/Open-Sewer-Issues#405]
All in the south-east corner.

These doors are not marked "ASDFOY" (by the way, what does it mean?), but seem not to be lockpickable:
#1:
![20190226204459_1](https://user-images.githubusercontent.com/8208481/53441690-a3468280-3a07-11e9-9857-b0e41e5f2e68.jpg)
#2:
![20190226204529_1](https://user-images.githubusercontent.com/8208481/53441693-a5104600-3a07-11e9-9b6e-b97d01105061.jpg)

These door use hitbox seems to be misaligned:
#1:
![20190226204553_1](https://user-images.githubusercontent.com/8208481/53441744-beb18d80-3a07-11e9-9356-fef0ddbcf75d.jpg)
![20190226204539_1](https://user-images.githubusercontent.com/8208481/53441746-c07b5100-3a07-11e9-83ca-6b0aba595743.jpg)
![20190226204548_1](https://user-images.githubusercontent.com/8208481/53441748-c2451480-3a07-11e9-92b5-eecd6998f739.jpg)

#2:
![20190226204855_1](https://user-images.githubusercontent.com/8208481/53441835-f91b2a80-3a07-11e9-8c0a-51604607370b.jpg)
![20190226204825_1](https://user-images.githubusercontent.com/8208481/53441839-fae4ee00-3a07-11e9-9a5f-dd7708139474.jpg)

**Comment by Oskutin** [comment]
https://en.wikipedia.org/wiki/Disc_tumbler_lock reference of Abloy.

**Comment by Epok13** [comment]
Thanks for the ref.

Actually, all the trailers doors seem to be misaligned.

**Comment by Epok13** [comment]
One more misaligned, but not a trailer door:
![20190226205249_1](https://user-images.githubusercontent.com/8208481/53442008-8494bb80-3a08-11e9-804f-9cc0b58cbd21.jpg)
