### ISSUE TITLE
Deekula storage lockpick

### ISSUE THREAD

**Issue by Epok13** [loiste-interactive/Open-Sewer-Issues#406]
In the storage, the locker is marked as "challenging" for lockpicking, but actually can be open without lockpicking it:
![20190226211002_1](https://user-images.githubusercontent.com/8208481/53443065-16052d00-3a0b-11e9-8848-4838e237c28c.jpg)
![20190226211124_1](https://user-images.githubusercontent.com/8208481/53443068-18678700-3a0b-11e9-94d3-b8f0ff62e96f.jpg)

(and still empty as everything else).

**Comment by Zuntti** [comment]
Fixed.
