### ISSUE TITLE
Deekula apartment 5B

### ISSUE THREAD

**Issue by Epok13** [loiste-interactive/Open-Sewer-Issues#407]
Two issues in this apartment:

- Main door opens the wrong way,
- Door inside bedroom marked "locked" but can't be lockpicked:
![20190226212617_1](https://user-images.githubusercontent.com/8208481/53444018-5fef1280-3a0d-11e9-8fcb-552eb6fc6a1c.jpg)
![20190226212615_1](https://user-images.githubusercontent.com/8208481/53444024-62516c80-3a0d-11e9-847f-aabc49647e36.jpg)

**Comment by Zuntti** [comment]
Fixed.
