### ISSUE TITLE
Objects accessible thru wall

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Open-Sewer-Issues#408]
Apartment 3B's refigenerator is accessible from stairwell by pointing on wall.
![image](https://user-images.githubusercontent.com/44178400/53443900-071f7a00-3a0d-11e9-9b72-c29e495fadd0.png)

**Comment by xiv72** [comment]
Actually, the same happens with the locker in the basement. If you go outside against the wall, you can access it also.

**Comment by Oskutin** [comment]
Seems to be universal proble,

**Comment by Kastuk** [comment]
Beer bottles trought the glass at the Factory.
![20190523131605_1](https://user-images.githubusercontent.com/36314945/58249253-032e9a00-7d67-11e9-8357-7c5b0cf5db4e.jpg)
