### ISSUE TITLE
Deekula apartment 7B

### ISSUE THREAD

**Issue by Epok13** [loiste-interactive/Open-Sewer-Issues#409]
Two issues with this apartment:

- Main door opens the wrong way,
- Balcony door opens the wrong way, and closes as soon as we step back, so almost impossible to pass through:
![20190226212955_1](https://user-images.githubusercontent.com/8208481/53444271-fd4a4680-3a0d-11e9-9467-0e20b9f32483.jpg)

**Comment by Zuntti** [comment]
Fixed.
