### ISSUE TITLE
Settings/options problem

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Open-Sewer-Issues#410]
Every time when I open the game, the Quality and Controls are resetting to:
![image](https://user-images.githubusercontent.com/44178400/53444479-8bbec800-3a0e-11e9-9164-2698163b42d8.png)
![image](https://user-images.githubusercontent.com/44178400/53444484-911c1280-3a0e-11e9-8084-5d291c561dbc.png)
Applying mouse sensitivity in menu is also resetted after loading game.

**Comment by Scarchu** [comment]
Yes, i've already reported that. #398
