### ISSUE TITLE
Missing door collision and function.

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Open-Sewer-Issues#411]
Player can easily move through door here, this door can't be interacted (open).
![image](https://user-images.githubusercontent.com/44178400/53511944-d1889880-3ac1-11e9-9254-445778492905.png)
![image](https://user-images.githubusercontent.com/44178400/53511950-d6e5e300-3ac1-11e9-8a7d-2ae1e80f1c99.png)
![image](https://user-images.githubusercontent.com/44178400/53511971-df3e1e00-3ac1-11e9-93a3-d7b914171aab.png)

**Comment by Zuntti** [comment]
Fixed.
