### ISSUE TITLE
Jumping off the map

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Open-Sewer-Issues#414]
Near prison and entrance to bazaar, it's possible to jump over the fence, that should keep player on map. By running on snow slop and jumping onto tent, then on tent's chimney, from chimney by using crouch-jump, jump over fence.
![image](https://user-images.githubusercontent.com/44178400/53702279-8c3bd200-3e05-11e9-8792-9a0d0f1e8641.png)
![image](https://user-images.githubusercontent.com/44178400/53702281-8e9e2c00-3e05-11e9-9949-1dcfa7c34073.png)

**Comment by Oskutin** [comment]
Fixed
