### ISSUE TITLE
Hole in the World

### ISSUE THREAD

**Issue by CVariable** [loiste-interactive/Open-Sewer-Issues#415]
There's a hole here. You can see the sewer water flow through it.
![20190310171621_1](https://user-images.githubusercontent.com/45665371/54092370-a4729a80-438b-11e9-8160-4144dc92b715.jpg)
![20190310171629_1](https://user-images.githubusercontent.com/45665371/54092373-a63c5e00-438b-11e9-82a2-98c3464e1b14.jpg)

**Comment by Oskutin** [comment]
Fixed
