### ISSUE TITLE
No toilet in own appartment?

### ISSUE THREAD

**Issue by xiv72** [loiste-interactive/Open-Sewer-Issues#421]
There is no toilet in your own appartment. Which doesn't make sense?

**Comment by Oskutin** [comment]
You'll receive one after upgrading it.

**Comment by xiv72** [comment]
i have no way to upgrade it further (i think). There is no more renovation possible. Is there a way?

**Comment by Oskutin** [comment]
Can you give me picture of the apartment, and upgrade screen?

**Comment by xiv72** [comment]
OK, so it seems there is a toilet, but I didn't see it, because when i put my cursor on the toilet door, it doesn't "say" anything (like door- open). But by pressing 'E' in front of it, it opened and i saw the toilet. BUT i cannot seem to be able to use it.

![Toilet Door](https://user-images.githubusercontent.com/48769546/55218357-2ffc8000-5202-11e9-97f6-4459560104f1.jpg)
![Toilet](https://user-images.githubusercontent.com/48769546/55218363-33900700-5202-11e9-94e9-ff616db37326.jpg)

**Comment by xiv72** [comment]
Now i can open the door, but i still can't use the toilet. It doesn't show any option when i point on it.

**Comment by Oskutin** [comment]
Fixed.
