### ISSUE TITLE
problems with areaportals

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Open-Sewer-Issues#423]
Doors to Deekula tenement (clearly shows base ground of the world)
![image](https://user-images.githubusercontent.com/44178400/55952178-3e628700-5c59-11e9-885b-0dd5b4b48c75.png)
walkway from graveyard along school
![image](https://user-images.githubusercontent.com/44178400/55952243-65b95400-5c59-11e9-97dd-31ffd9634b7a.png)
![image](https://user-images.githubusercontent.com/44178400/55952253-69e57180-5c59-11e9-9307-f22e462c15d9.png)
Rob's shop
![image](https://user-images.githubusercontent.com/44178400/55952265-6fdb5280-5c59-11e9-9bb7-073f22653797.png)
Omarket
![image](https://user-images.githubusercontent.com/44178400/55952269-75389d00-5c59-11e9-996f-dd0284b822ce.png)
graveyard (plus invisible orange shrooms but still pickable)
![image](https://user-images.githubusercontent.com/44178400/55952482-0576e200-5c5a-11e9-822d-3f75b7ccee9b.png)
weird faded out connection (it's not smooth, just one black instantly disappears)
![image](https://user-images.githubusercontent.com/44178400/55952339-a913c280-5c59-11e9-8344-c91deed92d5d.png)
![image](https://user-images.githubusercontent.com/44178400/55952346-add87680-5c59-11e9-8475-ee29a758b39a.png)
![image](https://user-images.githubusercontent.com/44178400/55952352-b03ad080-5c59-11e9-96aa-1d3499de9dd3.png)

**Comment by Oskutin** [comment]
Fixed

**Comment by Nextej** [comment]
Two more spots:
one again at back of graveyard
![20190412153309_1](https://user-images.githubusercontent.com/44178400/56041647-835dea80-5d39-11e9-85a5-bbab0d017861.jpg)
![20190412153313_1](https://user-images.githubusercontent.com/44178400/56041648-835dea80-5d39-11e9-9360-d5e1f0050b7a.jpg)
![20190412153316_1](https://user-images.githubusercontent.com/44178400/56041649-835dea80-5d39-11e9-8e53-679c6caa28d1.jpg)
![20190412153335_1](https://user-images.githubusercontent.com/44178400/56041650-835dea80-5d39-11e9-81f7-c1520a12c9b6.jpg)
![20190412153348_1](https://user-images.githubusercontent.com/44178400/56041651-83f68100-5d39-11e9-96f5-e72a8fa1b741.jpg)
window bug in house at front of deekula
![20190412153448_1](https://user-images.githubusercontent.com/44178400/56041686-9375ca00-5d39-11e9-97cf-c2af179580ea.jpg)
![20190412153451_1](https://user-images.githubusercontent.com/44178400/56041687-940e6080-5d39-11e9-90f3-907d57cc924a.jpg)

**Comment by Oskutin** [comment]
Fixed
