### ISSUE TITLE
Random names in character customization

### ISSUE THREAD

**Issue by Nextej** [loiste-interactive/Open-Sewer-Issues#425]
After using random name option on customization screen, in game it will be replaced with Esko Virtanen
![image](https://user-images.githubusercontent.com/44178400/56039203-05e3ab80-5d34-11e9-8085-a1e3b99e37f4.png)
![image](https://user-images.githubusercontent.com/44178400/56039207-0aa85f80-5d34-11e9-9eb1-9b52b062d992.png)

**Comment by Oskutin** [comment]
Hmm, Esko Virtanen, is the generic name, so seems that the name is not saved at all...

**Comment by Zuntti** [comment]
Fixed.
