### ISSUE TITLE
Off-map

### ISSUE THREAD

**Issue by xiv72** [loiste-interactive/Open-Sewer-Issues#429]
Close to the sauna, next to the construction site, if you move close to the building it allows you to go "off map"

![2019-04-13 17_19_54-Open Sewer](https://user-images.githubusercontent.com/48769546/56081744-e1113600-5e10-11e9-8576-d0eab92c09cc.jpg)

![2019-04-13 17_20_43-Open Sewer](https://user-images.githubusercontent.com/48769546/56081749-ecfcf800-5e10-11e9-8dbd-f9d32e40ebf2.jpg)

**Comment by Oskutin** [comment]
Fixed
