### ISSUE TITLE
Enhancement: possibility to have you own oven

### ISSUE THREAD

**Issue by xiv72** [loiste-interactive/Open-Sewer-Issues#430]
... right now only have my own stove...

**Comment by Oskutin** [comment]
Apartment IV upgrade when it'll be added.

**Comment by xiv72** [comment]
I don't have option to upgrade my flat anymore... will be this in the next update?

![image](https://user-images.githubusercontent.com/48769546/56424945-7ea5b300-62b2-11e9-9c76-82b2407e5e30.png)
