### ISSUE TITLE
Oven doesn't finish baking pizza :-(

### ISSUE THREAD

**Issue by xiv72** [loiste-interactive/Open-Sewer-Issues#432]
I put a pizza in the oven in appartment 3b, saved the game. When i restored the game, the oven seems stuck, and i clicking on abandon batch doesn't work anymore.

![2019-04-14 10_10_51-Open Sewer](https://user-images.githubusercontent.com/48769546/56090140-22035c00-5e9e-11e9-8c29-a16045028911.jpg)

**Comment by Oskutin** [comment]
Seems that it's done and ready for extracting.

Also that UI should be redesigned, because it's not intuitive.

**Comment by Oskutin** [comment]
Could also improve it so, that it shows whats in.

**Comment by xiv72** [comment]
How do i extract it? I tried to move the oven cloth on the place where there is "put items here", but it doesn't work. Also, is it normal it reads "Remaining" when it is done? And if i press "Abandon Batch", it doesn't work

**Comment by Oskutin** [comment]
Okay, now that sounds like a bug.
Can you upload your save here, so i can debug using it?
Found at: C:\Users\User\AppData\LocalLow\Loiste Interactive\Open Sewer

**Comment by xiv72** [comment]
[slot4_save.zip](https://github.com/loiste-interactive/Open-Sewer-Issues/files/3077860/slot4_save.zip)

**Comment by xiv72** [comment]
[slot4_save.zip](https://github.com/loiste-interactive/Open-Sewer-Issues/files/3077863/slot4_save.zip)

**Comment by Oskutin** [comment]
Saving and reloading that save resolved that.
Oven finished baking and i were able to extract pizza.

**Comment by Oskutin** [comment]
Game did complain that the save were from previous version, tho.

**Comment by Oskutin** [comment]
Fixed "Abandon batch"-button

**Comment by xiv72** [comment]
I'm not sure how you did that, because it doesn't work for me. I did like you said, i loaded it, saved it, and loaded it again, but still i see "remaining". Did you extract it immediately? or did you still wait for it to finish? how did you extract it? I tried taking the oven cloth and dropping it in "put items here".

I added my new save as well.

[slot6_save.zip](https://github.com/loiste-interactive/Open-Sewer-Issues/files/3092852/slot6_save.zip)


![image](https://user-images.githubusercontent.com/48769546/56338646-1b7d2900-61ab-11e9-8f1d-c287b1187f48.png)

**Comment by Oskutin** [comment]
Is the green bar progressing?
I had to wait a minute before i was able to extract.

**Comment by xiv72** [comment]
No, the green bar is not progressing. Waited for 10 mins..... it seems stuck

**Comment by Oskutin** [comment]
Are you on 0.1.5?

**Comment by xiv72** [comment]
How do i tell the version?

**Comment by Oskutin** [comment]
![vers](https://user-images.githubusercontent.com/5402150/56463667-81eb8c80-63e1-11e9-8546-8cbe7a94d0ed.png)

**Comment by xiv72** [comment]
Yes, 0.1.5

![image](https://user-images.githubusercontent.com/48769546/56472887-82793700-6464-11e9-8d19-400dd14a66ae.png)
