### ISSUE TITLE
Fishes floating on ice

### ISSUE THREAD

**Issue by Epok13** [loiste-interactive/Open-Sewer-Issues#434]
![20190415212858_1](https://user-images.githubusercontent.com/8208481/56159732-b5837c80-5fc5-11e9-9962-1bcc1ee0532f.jpg)
![20190415212920_1](https://user-images.githubusercontent.com/8208481/56159739-b74d4000-5fc5-11e9-9158-32b06144493e.jpg)

**Comment by Oskutin** [comment]
"Fixed"
