### ISSUE TITLE
World Disapearing & Fridge Glitch

### ISSUE THREAD

**Issue by Krolljr** [loiste-interactive/Open-Sewer-Issues#437]
I have 2 things, 
The first is that in a certain spot when you walk near the construction area near behind the police station the ground and buildings somehow disappear and all you can see is water.
The second glitch was I ended up opening a fridge through a wall in the deekula apartment block when I was coming down the stairs

**Comment by Oskutin** [comment]
Can you give photo of the exact spot?

**Comment by Krolljr** [comment]
![G1](https://user-images.githubusercontent.com/49819116/56464832-43d97300-63b7-11e9-92bb-dfcae1bf59ce.jpg)
![G2](https://user-images.githubusercontent.com/49819116/56464836-4936bd80-63b7-11e9-862f-e6ea8a6bacc7.jpg)

The first image is for the fridge part just in case you still might want it, and the second is the spot where I had the glitch a few times

**Comment by Oskutin** [comment]
Appears to be the same i alrady fixed: https://github.com/loiste-interactive/Open-Sewer-Issues/issues/429
