### ISSUE TITLE
Unlimited items multiplying in production devices

### ISSUE THREAD

**Issue by Kastuk** [loiste-interactive/Open-Sewer-Issues#442]
If you can leave buckets inside Mashing tun, they will multiply x2 after every opening of this device.
Same thing with Brewing barrel and any other items.

**Comment by Kastuk** [comment]
Then when I open any other container (like Trashbin), all this buckets will doubled here. If I move anything in that container, buckets will stay in that bin and disappear in the Masher tun.

**Comment by Oskutin** [comment]
Fixed
