### ISSUE TITLE
What is happening?

### ISSUE THREAD

**Issue by xiv72** [loiste-interactive/Open-Sewer-Issues#443]
Update seems to have stopped. Is this game still maintained? Are updates still coming?

**Comment by Oskutin** [comment]
working on minitrains

**Comment by xiv72** [comment]
copy / paste the code from Infra :-)

**Comment by deseven** [comment]
oh thanks, with this new knowledge he will be able to release everything tomorrow

**Comment by xiv72** [comment]
@deseven : it's called sarcasm....

**Comment by deseven** [comment]
yeah, i tried to make it sound sarcastic, guess it worked

**Comment by xiv72** [comment]
was referring to my comment .. works on both sides

**Comment by Nocktion** [comment]
"Sounds good, doesn't work"
