### ISSUE TITLE
Game runs smooth when not moving, moving drops framerate to unplayable level

### ISSUE THREAD

**Issue by babyavery** [loiste-interactive/Open-Sewer-Issues#445]
Purchased the game recently, using 0.1.7. Upon starting the beginning level, moving my character in any way drops the framerate from 60 to 15. It consistently ranges from 10-20 fps when moving only, when I stop moving it returns to normal. 

I tried updating to the beta, validating files thru steam, updating graphics drivers, etc. and the issue persisted. Prior to updating the drivers, moving the mouse would cause fps to drop, but that alone has stopped after a driver update. 

Specs:
Acer 144hz 1080p monitor (its possible the higher refresh rate may have something to do with it)
GTX 1060 3GB
i5-8400 @2.8 Ghz
8 GB Ram

**Comment by Oskutin** [comment]
There is massive overhaul going on because the lag and other issues.
