### ISSUE TITLE
hi. the alcohol store is closed all the time, i cant change money in the bank and my trader is out of money.

### ISSUE THREAD

**Issue by monikacska** [loiste-interactive/Open-Sewer-Issues#446]
so i tried to enter to that alcohol store many times fe. wednesday 9am, but its closed and says "mon-fri 8-17" or something like this... i went to the bank and i changed money, first time it was ok, but next time he said like~"i dont change more then that" so i cant hire that company to renovate my tenement.... i think the inventory is very small so i try to sell to the street trader everything i cant sell to the russian man, but it says he is out of money. i cant pick bottles coz i cant sell what i have and i dont want to waste them. sorry for my english im from hungary

**Comment by Oskutin** [comment]
There's major refactoring for the game in progress, we will try fix this for the refactored releases.
